plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\poude\\OneDrive\\Desktop\\biswash\\frontend\\Biswash\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\poude\\OneDrive\\Desktop\\biswash\\frontend\\Biswash"
command = "vite build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]